DROP SCHEMA IF EXISTS mstore CASCADE;
DROP USER IF EXISTS mstore_user;

CREATE USER mstore_user WITH PASSWORD 'mstore_pass';

CREATE SCHEMA IF NOT EXISTS mstore AUTHORIZATION mstore_user;

ALTER DEFAULT PRIVILEGES FOR USER mstore_user IN SCHEMA mstore GRANT ALL PRIVILEGES ON TABLES TO mstore_user;
ALTER DEFAULT PRIVILEGES FOR USER mstore_user IN SCHEMA mstore GRANT ALL PRIVILEGES ON SEQUENCES TO mstore_user;
ALTER DEFAULT PRIVILEGES FOR USER mstore_user IN SCHEMA mstore GRANT ALL PRIVILEGES ON FUNCTIONS TO mstore_user;
ALTER DEFAULT PRIVILEGES FOR USER mstore_user IN SCHEMA mstore GRANT ALL PRIVILEGES ON TYPES TO mstore_user;